version: "3"

services:
  localstack:
    image: "wolfgangmeyers/localstack_ngrep"
    ports:
      - "4569:4569" # dynamodb
      - "4572:4572" # S3
    environment:
      - SERVICES=s3,dynamodb
  dotnet:
    image: "microsoft/dotnet"
    volumes:
      - ./TestS3Client2:/TestS3Client2
    entrypoint: ["dotnet"]
    command: ["run"]
    working_dir: /TestS3Client2
    depends_on:
      - "localstack"

